### ISSUE TITLE
Add network policy on ROKS for CPD 4.5.0 Watson Discovery deployment

### ISSUE THREAD

**Issue by chuempel** [IBM/cloud-pak-deployer#111]
In order to successfully deploy **Watson Discovery** from the **CPD 4.5.0 GA** build on **ROKS**, we need to create a **network policy** in the **pre-install** phase in the **CPD instance namespace**. Would be great to include this pre-install step in the CP deployer playbooks.

The network policy should look like this .yaml:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    icpdsupport/addOnId: discovery
    icpdsupport/app: wd-discovery-kubeapi-egress-network-policy
    icpdsupport/empty-on-nd-backup: "true"
    icpdsupport/ignore-on-nd-backup: "true"
    owner: discovery
    service: discovery
    tenant: wd
  name: wd-discovery-kubeapi-egress-network-policy
spec:
  egress:
  - {}
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - ck-gen
      - cn-postgres-license-config
      - jks-secret
      - postgres-secret-gen
      - ranker-master
      - cn-postgres
    matchLabels:
      app.kubernetes.io/instance: wd
      app.kubernetes.io/name: discovery
  policyTypes:
  - Egress
```
