### ISSUE TITLE
CPD 4.5.1 on ROKS: Add special handling to install WKS

### ISSUE THREAD

**Issue by chuempel** [IBM/cloud-pak-deployer#127]
We need a special handling to install WKS (Watson Knowledge Studio) using the CP deployer.
While the apply-olm command works for WKS and successfully creates the CatalogSource and the Operator in ibm-common-services, WKS does not support apply-cr as of today.
Instead we need to install WKS using a .yaml file like the one below.
Could we add this to CP deployer? Thanks!

```
apiVersion: knowledgestudio.watson.ibm.com/v1
kind: KnowledgeStudio
metadata:
  name: wks     # This is the recommended name, but you can change it
  namespace: zen
spec:
  license:
    accept: true
  global:
    storageClassName: ocs-storagecluster-ceph-rbd
    size: small        # default size
```
