### ISSUE TITLE
CPD 4.5.0: OpenScale installation fails

### ISSUE THREAD

**Issue by chuempel** [IBM/cloud-pak-deployer#136]
While installing Data Science services from CPD 4.5.0 on ROKS Classis with NFS, the installation of OpenScale fails.
It appears, that the CR is not being created by the CP deployer and/or the OpenScale operator does not pickup the CR and remains idling The problem is occuring consistently on mulitple ROKS clusters (8 nodes, 16x64x300, 4TB NFS).

Currentl workaround is to run the CP deployer a 2nd time, but it would be great to get WOS installed at first time.

Error message is the following:
```
e does not exist in project zen", "[2022-09-15 16:57:51] Error: WOService object aiopenscale does not exist in project zen", "NAME     VERSION   BUILD        STATUS       AGE", "wml-cr   4.5.0     4.5.0-3409   InProgress   49m", "[2022-09-15 16:57:52] Info: Status of WMLBase object wml-cr is InProgress", "NAME    VERSION   RECONCILED   STATUS      AGE", "ws-cr   4.5.0     4.5.0        Completed   67m", "[2022-09-15 16:57:53] Info: Status of WS object ws-cr is Completed"]}}

PLAY RECAP *********************************************************************
localhost                  : ok=760  changed=151  unreachable=0    failed=1    skipped=573  rescued=0    ignored=0

Thursday 15 September 2022  16:57:53 +0000 (0:00:00.100)       5:02:54.451 ****
===============================================================================
cp4d-cartridge-install : Run apply-cr command to install cartridges, logs are in /home/user4/data/status/cluster-01/log/zen-apply-cr-cartridges.log  10502.13s
cp4d-cluster : Run apply-cr command to install Cloud Pak for Data platform, logs are in /home/user4/data/status/cluster-01/log/zen-apply-cr-cpd-platform.log  2602.10s
cp4d-catalog-source : Run apply-olm command to create catalog sources, logs are in /home/user4/data/status/cluster-01/log/apply-olm-create-catsrc.log  1551.28s
cp4d-subscriptions : Run apply-olm command to install cartridge subscriptions, logs are in /home/user4/data/status/cluster-01/log/zen-apply-olm-cartridge-sub.log  1542.56s
cp4d-subscriptions : Run apply-olm command to install platform subscriptions, logs are in /home/user4/data/status/cluster-01/log/zen-apply-olm-platform-sub.log - 531.70s
cp4d-subscriptions : Run preview script to install cartridge subscriptions, logs are in /home/user4/data/status/cluster-01/log/zen-apply-olm-cartridge-sub.log - 371.35s
cp4d-case-save : Run apply-olm command to download case files, logs are in /home/user4/data/status/cluster-01/log/apply-olm-case-save.log - 172.89s
cp4d-cartridge-install : Generate preview script to install cartridges, logs are in /home/user4/data/status/cluster-01/log/zen-apply-cr-cartridges.log - 149.25s
cp4d-subscriptions : Generate preview script to install platform subscriptions, logs are in /home/user4/data/status/cluster-01/log/zen-apply-olm-platform-sub.log -- 76.93s
cp4d-catalog-source : Generate preview script to create catalog sources, logs are in /home/user4/data/status/cluster-01/log/apply-olm-create-catsrc.log -- 56.20s
cp4d-case-save : Generate preview script to download case files, logs are in /home/user4/data/status/cluster-01/log/apply-olm-case-save.log -- 46.03s
cp4d-variables : Run list-components command --------------------------- 37.21s
cp-ocp-mco-pause : Check if MachineConfigPool exists for existing OpenShift -- 21.00s
openshift-download-client : Unpack OpenShift client from /home/user4/data/status/cluster-01/downloads/openshift-client-linux.tar.gz-4.10 -- 18.04s
cp4d-cartridge-install : Wait until cartridge analyticsengine has been installed, check logs in /home/user4/data/status/cluster-01/log/zen-cartridges.log -- 17.15s
cp4d-ocp-kubelet-config : Retrieve /etc/kubernetes/kubelet.conf -------- 13.32s
cp4d-login : Login to Cloud Pak for Data -------------------------------- 7.92s
cp4d-cartridge-remove : Check if cartridge db2 is currently installed --- 6.86s
cp4d-variables : Add versions details from olm-utils -------------------- 6.43s
cloudctl-download : Download cloudctl tool ------------------------------ 5.99s

====================================================================================
Deployer FAILED. Check previous messages. If command line is not returned, press ^C.

```

CP deployer config file is this file
cp4d-450.yaml:
```
---
cp4d:

- project: zen
  openshift_cluster_name: cluster-01
  cp4d_version: 4.5.0
  olm_utils: True
  use_case_files: True
  accept_licenses: True
  cartridges:
  - name: cp-foundation
    license_service:
      state: disabled
      threads_per_core: 2

  - name: lite

  - name: scheduler
    state: removed

#
# All tested cartridges. To install, change the "state" property to "installed". To uninstall, change the state
# to "removed" or comment out the entire cartridge. Make sure that the "-" and properties are aligned with the lite
# cartridge; the "-" is at position 3 and the property starts at position 5.
#
# If a cartridge has dependencies and you want to install it, you must ensure that the dependent cartridge is also
# installed.
#

  - name: analyticsengine
    size: small
    state: installed

  - name: bigsql
    state: removed

  - name: ca
    size: small
    instances:
    - name: ca-instance
      metastore_ref: ca-metastore
    state: removed

  - name: cde
    state: removed

  - name: datagate
    state: removed

  - name: datastage-ent-plus
    state: removed

  - name: db2
    state: installed

  - name: db2u
    state: removed

  - name: db2wh
    state: installed

  - name: dmc
    state: installed

  - name: dods
    size: small
    dependencies:
    - name: wsl
    - name: wml
    state: installed

  - name: dp
    size: small
    state: removed

  - name: dv
    size: small
    dependencies:
    - name: db2u
    instances:
    - name: data-virtualization
    state: removed

  # Please note that for EDB Postgress, a secret edb-postgres-license-key must be created in the vault
  # before deploying
  - name: edb_cp4d
    state: removed
    instances:
      - name: instance1
        version: "13.5"
        #type: Standard
        #members: 1
        #size_gb: 50
        #resource_request_cpu: 1000m
        #resource_request_memory: 4Gi
        #resource_limit_cpu: 1000m
        #resource_limit_memory: 4Gi

  - name: hadoop
    size: small
    dependencies:
    - name: wsl
    state: removed

  - name: mdm
    size: small
    wkc_enabled: true
    state: removed

  - name: openpages
    state: removed

  - name: planning-analytics
    state: removed

  - name: rstudio
    size: small
    dependencies:
    - name: wsl
    state: installed

  - name: spss
    dependencies:
    - name: wsl
    state: installed

  - name: voice-gateway
    replicas: 1
    state: removed

  - name: watson-assistant
    size: small
    state: removed

  - name: watson-discovery
    state: removed

  # For Watson Knowledge Studio, the case version is needed due to defect in olm utils
  # Not Released for 4.5.0
  - name: watson-ks
    size: small
    state: removed

  - name: watson-openscale
    size: small
    state: installed

  - name: watson-speech
    stt_size: xsmall
    tts_size: xsmall
    state: removed

  - name: wkc
    size: small
    state: removed

  - name: wml
    size: small
    state: installed

  - name: wml-accelerator
    replicas: 1
    size: small
    state: removed

  - name: wsl
    state: installed

#
# Cartridges where extra work is needed (will not install automatically)
#
  # Product Master requires set up of the Db2 instance secret before install
  - name: productmaster
    size: small
    state: removed
```

**Comment by chuempel** [comment]
Adding the other config file ocp-existing-roks-classic.yaml as well:
```
---
global_config:
  environment_name: sample
  cloud_platform: existing-ocp

openshift:
- name: cluster-01
  ocp_version: "4.10"
  cluster_name: c114-e
  domain_name: eu-de.containers.cloud.ibm.com
  openshift_storage:
  - storage_name: nfs-storage
    storage_type: nfs
# Use file storate class provided as part of ROKS cluster
    ocp_storage_class_file: managed-nfs-storage
    ocp_storage_class_block: managed-nfs-storage
```
