### ISSUE TITLE
Add banner to OpenShift console

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#147]
Allow specifying a banner to be added to the OpenShift console. This makes it easier to identify the OpenShift environment the user is working on.

Example:
```
openshift:
- name: cpd-demo
  ocp_version: 4.8
  cluster_name: cpd-demo
  domain_name: example.com
  infrastructure:
    type: detect
  console_banner: "FK-ITZ-SAML"
```
