### ISSUE TITLE
Support for Non ROSA AWS deployments

### ISSUE THREAD

**Issue by neilpatt** [IBM/cloud-pak-deployer#18]
**Is your feature request related to a problem? Please describe.**
Currently users can only use the deployer to deploy to ROSA on AWS

**Describe the solution you'd like**
I would like to see terraform being used to allow for deployment on self managed AWS infrastructure

**Describe alternatives you've considered**

**Additional context**

**Comment by fketelaars** [comment]
Tasks:

- [ ] Implement generator for AWS Terraform deployment template: https://github.com/ibm-cloud-architecture/terraform-openshift4-aws
- [ ] For most properties the defaults can be assumed
- [ ] Air-gapped is not in scope for this task
- [ ] Create new `openshift` configuration:
```
---
global_config:
  environment_name: sample
  cloud_platform: aws
  aws_region: eu-central-1

openshift:
- name: "{{ env_id }}"
  ocp_version: 4.8.24
  control_plane_flavour: m5.xlarge
  control_plane_nodes: 3
  compute_flavour: m5.4xlarge
  compute_nodes: 3
  infrastructure:
    type: standard-vpc
    aws_region: "{{ aws_region }}"
    multi_zone: True
    use_sts: False
  openshift_storage:
  - storage_name: ocs-storage
    storage_type: ocs
    ocs_storage_label: ocs
    ocs_storage_size_gb: 500
```

Type `type` depicts whether this is a ROSA (managed) or "standard-vpc" cluster. In case of `rosa`, the deployer already handles this. A new series of generators and scripts must be created to provision an OpenShift cluster on AWS using Terraform.

Check the `ibm-cloud` Terraform provisioning for examples on how to generate the Terraform scripts.

Important: Use the existing Terraform scripts as much as possible and try not to tweak them. Ideally, only the Terraform vars file should be changed by the generator. You could even consider to clone the golden configuration in GitHub at the time of deployment and generate the terraform tfvars file.

OpenShift storage does not have to be implemented, there is existing code for this already.

For your testing:
- Use `terraform init` to download the AWS provisioner
- Use `terraform plan` with AWS credentials to validate that syntax is ok and the cluster will generate
- Do not use `terraform apply`, this will be done later.
