### ISSUE TITLE
Option to create user defined DataStage Instances  

### ISSUE THREAD

**Issue by ThomasKrupski** [IBM/cloud-pak-deployer#226]
There is currently an option to create DataStage instances using the Deployer. The limitation is that, as in Cloud Pak for Data GUI, only T-shirt sizes can be selected. However, customers need the option to define the parameters of a DataStage instance more granularly.  It should be possible to specify the following parameters via configuration:

1. Number replicas px-runtime pods
2. Number of replicas px-compute pods
3. limits and requests for CPU and Memory per Pod-Type
4. storage class PVC
5. size PVC

**Comment by arthurlaimbock** [comment]
So item 4 & 5 can indeed be controlled by the Deployer configuration:

```
  - name: datastage-ent-plus
    state: removed
    #instances:
    #  - name: ds-instance
    #    # description: ds-instance provisioned by the deployer
    #    # size: small
    #    # storage_class: efs-nfs-client
    #    # storage_size_gb: 50
```
Description, size, storage_class and storage_size_gb are optional parameters. 

Unfortunately it is not recommended to "hack" the px-compute and px-runtime StatefulSets, as the StatefulSets that control these pods are controlled by the owning `PxRuntime` object. Here you can only define the tshirt size, for example:

```
  description: This is test-instance3 description
  license:
    accept: true
  parameters:
    scaleConfig: medium
    storageClass: efs-nfs-client
    storageSize: '60'
  version: 4.5.3
```

Although you can manually update the STS of Compute and Runtime, whenever the owning PxRuntime decides to re-run itself, it will **automatically** reset the STS back to its original settings as specified by the `scaleConfig` parameter. We find it too risky to update objects which are still being controlled by an owning object, in this case the PxRuntime. However if this is something you really want to do, it will be quite easy to generate your own `oc patch` commands that update the STS objects you want to alter. The naming conventions are quite straightforward to be generated in a script.

**Comment by ThomasKrupski** [comment]
It's recommened here to adjust the cr for the instamce to change replicas for compute and runtime pods and also pod size:
https://www.ibm.com/docs/en/cloud-paks/cp-data/4.5.x?topic=resources-enabling-multiple-conductor-pods

# retrieve pxruntime cr
oc get pxruntime

# edit pxruntime cr
oc edit pxruntime <cr-name>

spec:
  ignoreForMaintenance: false  # set to true to ignore refresh
  scale:                                        # override the t-shirt size
    pxcompute:           
      replicas: 2
      resources:
        limits:
          cpu: 3
          memory: 8Gi
        requests:
          cpu: 1
          memory: 2Gi
    pxruntime:
      replicas: 2
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 2Gi

**Comment by arthurlaimbock** [comment]
ah, thank you for this. If indeed we can modify this in the `cr` I will implement this.

**Comment by arthurlaimbock** [comment]
@ThomasKrupski  I have implemented the change, PR is under review at the moment:

You can specify the px_runtime and px_compute (both options must be provided if you use custom scale options) using the following example in your cp4d.yaml configuration file: 

```
  - name: datastage-ent-plus
    state: installed
    instances:
      - name: test-instance11
        description: "This is test-instance11 description"
        size: medium
        #storage_class: efs-nfs-client
        storage_size_gb: 60
        scale_px_runtime:
          replicas: 2
          cpu_request: 500m
          cpu_limit: 2
          memory_request: 2Gi
          memory_limit: 4Gi
        scale_px_compute:
          replicas: 2
          cpu_request: 1
          cpu_limit: 3
          memory_request: 4Gi
          memory_limit: 12Gi
```
