### ISSUE TITLE
Support private-only ROKS cluster

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#26]
ROKS supports provisioning of a cluster without public API and ingress endpoints. Add a property to the `openshift` object for ROKS to allow setting this flag at provisioning time.

```
openshift:
- name: "{{ env_id }}"
  ocp_version: 4.8
  compute_flavour: bx2.16x64
  compute_nodes: 3
  infrastructure:
    type: vpc
    vpc_name: "{{ env_id }}"
    subnets: 
    - "{{ env_id }}-subnet-zone-1"
    - "{{ env_id }}-subnet-zone-2"
    - "{{ env_id }}-subnet-zone-3"
    cos_name: "{{ env_id }}-cos"
    private_only: True
```
