### ISSUE TITLE
update documentation and usage of expandWith(matchPattern, remoteIdentifier='name')

### ISSUE THREAD

**Issue by rhocheck** [IBM/cloud-pak-deployer#28]
expandWith is always used with wildcard as shown in the documentation. In nested structured this will result in multiple matches

```
cos:
- name: {{ env_id }}-cos
  plan: standard
  location: global
  buckets:
  - name: bucket123
    region_location: eu-de
```

If you want the cos instance, expandWith(cos[*].name) won't work. You have to use expandWith(cos[0].name) 

I had to study the docs of benedict to find out proper usage of match.
