### ISSUE TITLE
Ability to specify WKC install options upfront/pre-install (enableMANTA, enableDataQuality, enableKnowledgeGraph, install_wkc_core_only)

### ISSUE THREAD

**Issue by tamara-tatian** [IBM/cloud-pak-deployer#289]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to specify WKC install options up front - instead, you have to edit the YAML post-factum to enable additional features like Semantic Search+Business Lineage, Nextgen DQ rules and Automated Data Lineage/MANTA components. 
There is also the WKC "core" vs "base" choice in the YAML (core will not install XMETA stack) - may be worth considering but for me personally not critical as I need "base" (extended), plus this choice will likely go away post 4.7. 

**Describe the solution you'd like**
Would be good to be able to specify your preferred options up front.  
https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=catalog-installing

**Describe alternatives you've considered**
Manual YAML edit post-install.

**Additional context**
![image](https://user-images.githubusercontent.com/111134185/210354773-b259c614-d903-4368-9b11-bedf9974f093.png)

**Comment by fketelaars** [comment]
@tamara-tatian It is currently possible to configure the options as part of the initial installation:
```
-   name: wkc
    size: small
    state: installed
    installation_options:
      enableDataQuality: true
      enableMANTA: true
      enableKnowledgeGraph: true
```

This will cause these options to be set directly during the installation. Moreover, if you set `sequential_install` to `False` in the `cp4d` properties, the CR will be created immediately with the selected options.
