### ISSUE TITLE
Add cluster name to log forwarding entries

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#29]
**Description**
When forwarding entries for multiple clusters, it may be difficult to identify the originating cluster, especially for namespaces that exist in every Cloud Pak cluster, such as `ibm-common-services` or the `openshift-*` ones.

**Change**
Add a label to the `ClusterLogForwarder` that indicates the cluster name.

```
   - inputRefs: 
      - application
     outputRefs:
      - loki-application
     labels:
       cluster-name: "fke37a"
```

We could allow more than 1 label in the `openshift_logging` object:
```
openshift_logging:
- openshift_cluster_name: sample
  cluster_wide_logging:
  - input: application
    logging_name: loki-application
    labels:
      cluster-name: "{{ env_id }}"
      region: "eu-de"
  - input: infrastructure
    logging_name: loki-application
  - input: audit
    logging_name: loki-audit
  logging_output:
  - name: loki-application
    type: loki
    url: https://loki-application.sample.com
    certificates:
      cert: {{ env_id }}-loki-cert
      key: {{ env_id }}-loki-key
      ca: {{ env_id }}-loki-ca
  - name: loki-audit
    type: loki
    url: https://loki-audit.sample.com
    certificates:
      cert: {{ env_id }}-loki-cert
      key: {{ env_id }}-loki-key
      ca: {{ env_id }}-loki-ca
```
