### ISSUE TITLE
Install on existing VPC ignores specified subnets for zone

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#297]
**Describe the bug**
When running the deployer against an existing VPC and the config specifies the subnets OpenShift must be installed onto, the zones(s) of the subnet(s) are ignored and the zone of the first subnet in the VPC is specified in the AWS configuration.

Error reported:
```
level=info msg=Credentials loaded from default AWS environment variables
level=fatal msg=failed to fetch Metadata: failed to load asset "Install Config": [platform.aws.subnets[0]: Invalid value: "subnet-0549812ddc88d2316": subnet's CIDR range start 172.16.160.0 is outside of the specified machine networks, platform.aws.subnets[1]: Invalid value: "subnet-0b1c9a808f90ec980": subnet's CIDR range start 172.16.32.0 is outside of the specified machine networks, controlPlane.platform.aws.zones: Invalid value: []string{"eu-central-1a"}: No subnets provided for zones [eu-central-1a], compute[0].platform.aws.zones: Invalid value: []string{"eu-central-1a"}: No subnets provided for zones [eu-central-1a]]
```

**To Reproduce**
```
  infrastructure:
    type: self-managed
    aws_region: "{{ aws_region }}"
    multi_zone: False
    use_sts: False
    machine_cidr: 10.1.0.0/24
    subnet_ids:
    - subnet-0549812ddc88d2316
    - subnet-0b1c9a808f90ec980
```

Produced install-config.yaml:
```
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: m5.xlarge
      zones: ['eu-central-1a']
  replicas: 3

compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: m5.xlarge
      zones: ['eu-central-1a']
  replicas: 3
```

Rather than picking the zone of the first subnet, the zone(s) of the specified subnet IDs must be picked.

**Workaround**
Select subnets of the first zone of the VPC.
