### ISSUE TITLE
Failure when installing operators

### ISSUE THREAD

**Issue by triceam** [IBM/cloud-pak-deployer#301]
**Describe the bug**
I'm seeing failures when the deployer is installing operators/subscriptions.  This is in an existing OCP 4.10 cluster, with the deployer running in a job inside the cluster (gitops configuration).

In the logs I see: 
```

TASK [cp4d-subscriptions : Run apply-olm command to install cartridge subscriptions, logs are in /Data/cpd-status/log/cpd-instance-apply-olm-cartridge-sub.log] ***
Wednesday 18 January 2023 20:13:45 +0000 (0:00:00.263) 0:21:19.274 *****
FAILED - RETRYING: Run apply-olm command to install cartridge subscriptions, logs are in /Data/cpd-status/log/cpd-instance-apply-olm-cartridge-sub.log (2 retries left).
FAILED - RETRYING: Run apply-olm command to install cartridge subscriptions, logs are in /Data/cpd-status/log/cpd-instance-apply-olm-cartridge-sub.log (1 retries left).
changed: [localhost]
TASK [cp4d-subscriptions : Retrieving state of all operators in project ibm-common-services] ***
Wednesday 18 January 2023 20:26:53 +0000 (0:13:07.476) 0:34:26.750 *****
changed: [localhost]
TASK [cp4d-subscriptions : fail] ***********************************************
Wednesday 18 January 2023 20:26:53 +0000 (0:00:00.479) 0:34:27.229 *****
fatal: [localhost]: FAILED! => changed=false
msg: 'Creation of the subscriptions failed (possible due to OLM issue): [''ibm-common-service-operator,2023-01-18T20:13:57Z,ibm-common-service-operator.v3.19.0,AtLatestKnown'', ''ibm-namespace-scope-operator,2023-01-18T20:14:45Z,ibm-namespace-scope-operator.v1.13.0,AtLatestKnown'', ''operand-deployment-lifecycle-manager-app,2023-01-18T20:15:52Z,operand-deployment-lifecycle-manager.v1.17.0,AtLatestKnown'', ''cpd-operator,2023-01-18T20:18:00Z,cpd-platform-operator.v3.0.0,AtLatestKnown'', ''ibm-cpd-ccs-operator,2023-01-18T20:18:03Z,ibm-cpd-ccs.v2.0.0,AtLatestKnown'', ''ibm-db2u-operator,2023-01-18T20:18:05Z,db2u-operator.v2.0.0,AtLatestKnown'', ''redis-operator,2023-01-18T20:18:07Z,ibm-cloud-databases-redis.v1.5.1,AtLatestKnown'', ''ibm-dmc-operator-subscription,2023-01-18T20:18:10Z,ibm-databases-dmc.v1.5.0,AtLatestKnown'', ''ibm-dv-operator-catalog-subscription,2023-01-18T20:18:12Z,ibm-dv-operator.v1.8.0,AtLatestKnown'']'
PLAY RECAP *********************************************************************
localhost : ok=592 changed=99 unreachable=0 failed=1 skipped=294 rescued=0 ignored=0
Wednesday 18 January 2023 20:26:53 +0000 (0:00:00.032) 0:34:27.261 *****
===============================================================================
cp4d-catalog-source : Run apply-olm command to create catalog sources, logs are in /Data/cpd-status/log/apply-olm-create-catsrc.log - 932.01s
cp4d-subscriptions : Run apply-olm command to install cartridge subscriptions, logs are in /Data/cpd-status/log/cpd-instance-apply-olm-cartridge-sub.log - 787.48s
cp4d-case-save : Run apply-olm command to download case files, logs are in /Data/cpd-status/log/apply-olm-case-save.log -- 77.35s
cp4d-variables : Run list-components command --------------------------- 36.63s
cp4d-subscriptions : Generate preview script to install cartridge subscriptions, logs are in /Data/cpd-status/log/cpd-instance-apply-olm-cartridge-sub.log -- 35.37s
cp4d-catalog-source : Generate preview script to create catalog sources, logs are in /Data/cpd-status/log/apply-olm-create-catsrc.log -- 30.70s
cp4d-case-save : Generate preview script to download case files, logs are in /Data/cpd-status/log/apply-olm-case-save.log -- 26.23s
cp4d-ocp-kubelet-config : Retrieve /etc/kubernetes/kubelet.conf --------- 9.00s
openshift-download-client : Unpack OpenShift client from /Data/cpd-status/downloads/openshift-client-linux.tar.gz-4.8 --- 8.10s
cpd-cli-download : Unpack cpd-cli from /Data/cpd-status/downloads/cpd-cli-linux-amd64.tar.gz --- 8.00s
====================================================================================
Deployer FAILED. Check previous messages. If command line is not returned, press ^C.
```

It looks like the deployer is timing out when creating operator subscriptions.  I saw the first `FAILED - RETRYING: Run apply-olm command to install cartridge subscriptions, logs are in /Data/cpd-status/log/cpd-instance-apply-olm-cartridge-sub.log (2 retries left).` message, and noticed one of the operator subscriptions hadn't completed successfully.  When it was re-running, I deleted the "stuck" operator, and it proceeded to deploy correctly.

For this last failure, I do not see any stuck or failed deployments or events on the cluster, but it errored out nonetheless. Here's what I see for installed operators:

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/974294/213288449-d21eb5ad-b8f5-4b60-9d5b-3b6b41e81193.png">

**Expected behavior**
I expected the installation to proceed without any problems.

**Comment by triceam** [comment]
Note: That screenshot of installed operators does not contain all operators for what I expected to be installed.

Here's the config that I am attempting to deploy:

```
---
global_config:
  environment_name: cloud-pak-for-data
  cloud_platform: existing-ocp

openshift:
- name: cloud-pak-for-data
  ocp_version: 4.8
  cluster_name: cloud-pak-for-data
  domain_name: amt-data-fabric-0ed2b1307d0ce0e0627ae949f443cd72-0000.us-east.containers.appdomain.cloud
  openshift_storage:
  - storage_name: ocs-storage
    storage_type: ocs
    ocs_storage_label: ocs
    ocs_storage_size_gb: 500

cp4d:
- project: cpd-instance
  openshift_cluster_name: cloud-pak-for-data
  cp4d_version: 4.5.0
  sequential_install: True
  accept_licenses: true
  cartridges:

  - name: cp-foundation
    license_service:
      state: disabled
      threads_per_core: 2

  - name: lite

  - name: scheduler 
    state: removed 

#
# All tested cartridges. To install, change the "state" property to "installed". To uninstall, change the state
# to "removed" or comment out the entire cartridge. Make sure that the "-" and properties are aligned with the lite
# cartridge; the "-" is at position 3 and the property starts at position 5.
#

  - name: analyticsengine 
    size: small 
    state: removed 

  - name: bigsql
    state: removed 

  - name: ca
    size: small
    instances:
    - name: ca-instance
      metastore_ref: ca-metastore
    state: removed 

  - name: cde
    state: removed 

  - name: datagate
    state: removed 

  - name: datastage-ent-plus
    state: removed 
    # instances:
    #   - name: ds-instance
    #     # Optional settings
    #     description: "datastage ds-instance"
    #     size: medium
    #     storage_class: efs-nfs-client
    #     storage_size_gb: 60
    #     # Custom Scale options
    #     scale_px_runtime:
    #       replicas: 2
    #       cpu_request: 500m
    #       cpu_limit: 2
    #       memory_request: 2Gi
    #       memory_limit: 4Gi
    #     scale_px_compute:
    #       replicas: 2
    #       cpu_request: 1
    #       cpu_limit: 3
    #       memory_request: 4Gi
    #       memory_limit: 12Gi    

  - name: db2
    size: small
    instances:
    - name: ca-metastore
      metadata_size_gb: 20
      data_size_gb: 20
      backup_size_gb: 20  
      transactionlog_size_gb: 20
    state: removed 

  - name: db2u
    state: removed 

  - name: db2wh
    state: removed 

  - name: dmc
    state: removed 

  - name: dods
    size: small
    state: removed 

  - name: dp
    size: small
    state: removed 

  - name: dv
    size: small 
    instances:
    - name: data-virtualization
    state: installed 

  - name: hadoop
    size: small
    state: removed 

  - name: mdm
    size: small
    wkc_enabled: true
    state: removed 

  - name: openpages
    state: removed 

  - name: planning-analytics
    state: removed 

  - name: rstudio
    size: small
    state: removed 

  - name: spss
    state: removed 

  - name: voice-gateway
    replicas: 1
    state: removed 

  - name: watson-assistant
    size: small
    state: removed 

  - name: watson-discovery
    state: removed 

  - name: watson-ks
    size: small
    state: installed 

  - name: watson-openscale
    size: small
    state: removed 

  - name: watson-speech
    stt_size: xsmall
    tts_size: xsmall
    state: removed 

  - name: wkc
    size: small
    state: installed 

  - name: wml
    size: small
    state: installed 

  - name: wml-accelerator
    replicas: 1
    size: small
    state: removed 

  - name: wsl
    state: removed
```
