### ISSUE TITLE
Specify wkc options on initial install

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#357]
**Describe the bug**
If WKC is installed with `install_wkc_core_only: True` this option must be set in the parameter file, otherwise there's a chance the iis and wkc Db2 statefulsets are created anyway.

**Resolution**
- [ ] Add parameter file to apply-cr command, if it exists
- [ ] Specify WKC options in this parameter file like this:
```
custom_spec:
  wkc:
    install_wkc_core_only: True
  other_service:
    foo: bar
```
- [ ] Update Replication to also apply parameter file like this so it won't require a separate install anymore
