### ISSUE TITLE
Provide config sample for cloud satellite

### ISSUE THREAD

**Issue by b-alazard** [IBM/cloud-pak-deployer#406]
**Is your feature request related to a problem? Please describe.**
In my case, we are using other storage class names  for odf on IBM cloud satellite, which caused the detection of roks to fail.

```
sat-ocs-cephfs-gold       
sat-ocs-cephfs-gold-metro
sat-ocs-cephrbd-gold         
sat-ocs-cephrbd-gold-metro 
sat-ocs-cephrgw-gold         
```

**Describe the solution you'd like**

A sample config for cloud satellite would help.
We currently fixed the infrastructure detection by adding infrastruture type in `ocp-existing-roks-classic.yaml

```
 infrastructure: 
    type: ibm-roks
```  

**Describe alternatives you've considered**

**Additional context**

CP4D deployment was successfull with this configuration.

```
---
global_config:
  environment_name: sample
  cloud_platform: existing-ocp
  env_id:  "{{ env_id }}"
openshift:
- name: "{{ env_id }}"
  ocp_version: "4.10"
  cluster_name: "{{ env_id }}"
  domain_name: example.appdomain.com
  infrastructure: 
    type: ibm-roks
  openshift_storage:
  - storage_name: ocs-storagecluster
    storage_type: custom
# Use file storate class provided as part of ROKS cluster
    ocp_storage_class_file: sat-ocs-cephfs-gold
    ocp_storage_class_block: sat-ocs-cephrbd-gold
```
