### ISSUE TITLE
Curated list of available catridges

### ISSUE THREAD

**Issue by Max-Jesch** [IBM/cloud-pak-deployer#415]
Finding how to describe the components  (aka cartridges) you want to install into your CP4D in the config files can be tricky. For Example: It took me quiet some time to find out that "Cognos Analytics" is called "ca" and I still don't know which options I have for configuring it

It would be great to have a document that details all the tested components (aka cartridges) that can be installed into a cloud pak and the options that are available for configuring them.

**Comment by fketelaars** [comment]
Under `sample-configurations` find all `cp4d*` yaml files and add a description to the cartridges. Most descriptions can be retrieved from `sample-configurations/web-ui-base-config/cloud-pak/cp4d.yaml`.

```
  - name: analyticsengine 
    description: Analytics Engine Powered by Apache Spark
    size: small 
    state: removed

  - name: bigsql
    description: Db2 Big SQL    
    state: removed

  - name: ca
    description: Cognos Analytics
    size: small
    instances:
    - name: ca-instance
      metastore_ref: ca-metastore
    state: removed
```
