### ISSUE TITLE
Mac OS Support for CP4D deployment

### ISSUE THREAD

**Issue by b-alazard** [IBM/cloud-pak-deployer#417]
**Is your feature request related to a problem? Please describe.**

Would it be much effort to enable support for Mac for CP4D deployment?
Since podman on Mac now works well, also with volume mount, it would be quite convenient.

**Describe the solution you'd like**
We have identified the following current issues:

##### Mounting volumes with :z 
It does not work on Mac. :z could be set in a variable depending on which OS is dectected. OS detection could be done by getenforce (for SE - Linux systems)  or with existing path to OS-release files ?

e.g taken from [Rainer's fork](https://github.ibm.com/Rainer-Hochecker/satellite-deployer/blob/mvi/sat-deploy.sh) , but works only for SE Linux.

```
# check selinux
SE_LINUX_OPTION=""
if hash getenforce 2>/dev/null; then
  SELINUXSTATUS=$(getenforce)
  if [ "$SELINUXSTATUS" != "Disabled" ]; then
    SE_LINUX_OPTION=":z"
  fi
fi
```

##### Unarchive of cloudctl download fails

[Unarchive of cloudctl](https://github.com/IBM/cloud-pak-deployer/blob/f6773a4895cb19149dc1a0b7ca8b7bc147c1b67f/automation-roles/99-generic/cloudctl/cloudctl-download/tasks/main.yml) download fails with permissions denied while gtar is trying to `chown 0 gid 0` on the extracted file in mounted volume.

The cloudctl download could be extracted directly in container file system ("/usr/local/bin"), like it is done for [ocp client](https://github.com/IBM/cloud-pak-deployer/blob/f6773a4895cb19149dc1a0b7ca8b7bc147c1b67f/automation-roles/99-generic/openshift/openshift-download-client/tasks/main.yml) 

```
- name: Unpack cloudctl from {{ status_dir }}/downloads/cloudctl-linux-amd64.tar.gz
  unarchive:
    src: "{{ status_dir }}/downloads/cloudctl-linux-amd64.tar.gz"
    dest: "{{ status_dir }}/downloads"
```

**Describe alternatives you've considered**

**Additional context**

There might be additional issues for Mac, but we were already stuck at those 2.
