### ISSUE TITLE
Using cloud satellite ODF storage classes for cp4d

### ISSUE THREAD

**Issue by b-alazard** [IBM/cloud-pak-deployer#436]
When ODF is deployed using the [Satellite storage template](https://cloud.ibm.com/docs/satellite?topic=satellite-storage-template-ov#storage-template-ov-providers) for odf-local devices , the ODF satellite storage classes must be specified.

```
  openshift_storage:
  - storage_name: ocs-storagecluster
    storage_type: custom
# Use storate classes provided bei Satellite ODF template
    ocp_storage_class_file: sat-ocs-cephfs-gold
    ocp_storage_class_block: sat-ocs-cephrbd-gold
```

If they are not specified , the cp-deployer will use the standard odf  storage classes.
