### ISSUE TITLE
Installing of WS runtimes fails

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#450]
**Describe the bug**
When installing the WS runtimes through the preview scripts, the following is included in the preview.sh:
```
#  applying CR for Watson Studio Runtimes
cat <<EOF |oc apply -f -
apiVersion: ws.cpd.ibm.com/v1beta1
kind: NotebookRuntime
metadata:
  name: <only include 'ws_runtimes' in '--components' when installing an individual runtime or when upgrading from CPD 4.x>
  namespace: cpd
  labels:
    app.kubernetes.io/instance: notebookruntime
    app.kubernetes.io/managed-by: ibm-cpd-ws-runtimes-operator
    app.kubernetes.io/name: ibm-cpd-ws-runtimes
spec:
  kind: <only include 'ws_runtimes' in '--components' when installing an individual runtime or when upgrading from CPD 4.x>
  version: 6.5.0

EOF
```

It appears that the ws_runtimes must be installed individually, one by one. Running the following command manually worked:
```
./cpd-cli manage apply-cr --release=4.6.6 --components=ws_runtimes --license_acceptance=true --cpd_instance_ns=cpd --extra-vars="cr_name=ibm-cpd-ws-runtime-222-r"
```

https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=42-installing

Actions:

- [x] Update `automation-roles/50-install-cloud-pak/cp4d/cp4d-variables/vars/vars-cp4d-installation.yml` and make sure that `ws-runtimes` is installed separately: `separate_install: True`
- [x] Ensure that the installation of ws-runtimes is separate and installing each runtime one by one
