### ISSUE TITLE
Surviving Cardridge selection not working with Datastage

### ISSUE THREAD

**Issue by ronanb3** [IBM/cloud-pak-deployer#452]
When upgrading the DataStage Enterprise Plus Cartridge, I have the following error.
```
TASK [cp4d-cartridge-remove : Fail if destroy was not confirmed] ***************
task path: /cloud-pak-deployer/automation-roles/50-install-cloud-pak/cp4d/cp4d-cartridge-remove/tasks/cp4d-remove-cr.yml:2
Monday 12 June 2023  09:37:00 +0000 (0:00:00.052)       0:45:09.167 ***********
fatal: [localhost]: FAILED! => changed=false
  msg: Will not delete cartridge datastage-ent. Destroy was not confirmed with --confirm-destroy parameter or global_config confirm_destroy property
```

Here is the log part involved

```
ok: [localhost] => (item=ws-pipelines) => changed=false 
  ansible_facts:
    _surviving_cartridges:
    - CASE_Name: ibm-wml-cpd
      CASE_Version: 6.4.0
      CR_API: wml.cpd.ibm.com
      CR_Kind: WmlBase
      CR_Name: wml-cr
      CR_Version: 4.6.4
      Component_name: wml
      Dependencies: ccs
      Description: Watson Machine Learning
      Is_Automatic_Dependency: ''
      Operator_CSV_Version: 3.4.0
      Supported_Architecture: amd64/ppc64le/s390x
      cartridge_label: operators.coreos.com/ibm-cpd-wml-operator.ibm-common-services
      case_dependencies:
      - ccs
      cr_cr: WMLBase
      cr_file_prefix: wml
      cr_name: wml-cr
      cr_operator_label: ibm-wml-cpd
      cr_status_attribute: wmlStatus
      cr_status_completed: Completed
      download_dependent_case: false
      force_sequential_install: false
      inventory: wmlOperatorSetup
      name: wml
      olm_utils_name: wml
      package_manifest: ibm-cpd-wml-operator
      search_string: ibm-wml-cpd
      size: small
      state: installed
    - CASE_Name: ibm-wml-cpd
      CASE_Version: 6.4.0
      CR_API: wml.cpd.ibm.com
      CR_Kind: WmlBase
      CR_Name: wml-cr
      CR_Version: 4.6.4
      Component_name: wml
      Dependencies: ccs
      Description: Watson Machine Learning
      Is_Automatic_Dependency: ''
      Operator_CSV_Version: 3.4.0
      Supported_Architecture: amd64/ppc64le/s390x
      cartridge_label: operators.coreos.com/ibm-cpd-wml-operator.ibm-common-services
      case_dependencies:
      - ccs
      cr_cr: WMLBase
      cr_file_prefix: wml
      cr_name: wml-cr
      cr_operator_label: ibm-wml-cpd
      cr_status_attribute: wmlStatus
      cr_status_completed: Completed
      download_dependent_case: false
      force_sequential_install: false
      inventory: wmlOperatorSetup
      name: wml
      olm_utils_name: wml
      package_manifest: ibm-cpd-wml-operator
      search_string: ibm-wml-cpd
      size: small
      state: installed
    - CASE_Name: ibm-wml-cpd
      CASE_Version: 6.4.0
      CR_API: wml.cpd.ibm.com
      CR_Kind: WmlBase
      CR_Name: wml-cr
      CR_Version: 4.6.4
      Component_name: wml
      Dependencies: ccs
      Description: Watson Machine Learning
      Is_Automatic_Dependency: ''
      Operator_CSV_Version: 3.4.0
      Supported_Architecture: amd64/ppc64le/s390x
      cartridge_label: operators.coreos.com/ibm-cpd-wml-operator.ibm-common-services
      case_dependencies:
      - ccs
      cr_cr: WMLBase
      cr_file_prefix: wml
      cr_name: wml-cr
      cr_operator_label: ibm-wml-cpd
      cr_status_attribute: wmlStatus
      cr_status_completed: Completed
      download_dependent_case: false
      force_sequential_install: false
      inventory: wmlOperatorSetup
      name: wml
      olm_utils_name: wml
      package_manifest: ibm-cpd-wml-operator
      search_string: ibm-wml-cpd
      size: small
      state: installed
    - CASE_Name: ibm-wml-cpd
      CASE_Version: 6.4.0
      CR_API: wml.cpd.ibm.com
      CR_Kind: WmlBase
      CR_Name: wml-cr
      CR_Version: 4.6.4
      Component_name: wml
      Dependencies: ccs
      Description: Watson Machine Learning
      Is_Automatic_Dependency: ''
      Operator_CSV_Version: 3.4.0
      Supported_Architecture: amd64/ppc64le/s390x
      cartridge_label: operators.coreos.com/ibm-cpd-wml-operator.ibm-common-services
      case_dependencies:
      - ccs
      cr_cr: WMLBase
      cr_file_prefix: wml
      cr_name: wml-cr
      cr_operator_label: ibm-wml-cpd
      cr_status_attribute: wmlStatus
      cr_status_completed: Completed
      download_dependent_case: false
      force_sequential_install: false
      inventory: wmlOperatorSetup
      name: wml
      olm_utils_name: wml
      package_manifest: ibm-cpd-wml-operator
      search_string: ibm-wml-cpd
      size: small
      state: installed
    - {}
    - CASE_Name: ibm-wml-cpd
      CASE_Version: 6.4.0
      CR_API: wml.cpd.ibm.com
      CR_Kind: WmlBase
      CR_Name: wml-cr
      CR_Version: 4.6.4
      Component_name: wml
      Dependencies: ccs
      Description: Watson Machine Learning
      Is_Automatic_Dependency: ''
      Operator_CSV_Version: 3.4.0
      Supported_Architecture: amd64/ppc64le/s390x
      cartridge_label: operators.coreos.com/ibm-cpd-wml-operator.ibm-common-services
      case_dependencies:
      - ccs
      cr_cr: WMLBase
      cr_file_prefix: wml
      cr_name: wml-cr
      cr_operator_label: ibm-wml-cpd
      cr_status_attribute: wmlStatus
      cr_status_completed: Completed
      download_dependent_case: false
      force_sequential_install: false
      inventory: wmlOperatorSetup
      name: wml
      olm_utils_name: wml
      package_manifest: ibm-cpd-wml-operator
      search_string: ibm-wml-cpd
      size: small
      state: installed
    - {}
    - {}
  ansible_loop_var: item
  item: ws-pipelines
```
