### ISSUE TITLE
WKC 4.5.0 fails to install due to missing SCC

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#48]
**Describe the bug**
SCCs and service accounts have been renamed in CP4D 4.5. Adjust SCC and polcy assignment accordingly.

```
#  applying SCC for Watson Knowledge Catalog add-on
cat <<EOF |oc apply -f -
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: WKC/IIS provides all features of the restricted SCC
      but runs as user 10032.
  name: wkc-iis-scc
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAs
  uid: 10032
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret

EOF

#  adding SCC to user  for Watson Knowledge Catalog add-on
oc adm policy add-scc-to-user wkc-iis-scc system:serviceaccount:zen-450:wkc-iis-sa
```
