### ISSUE TITLE
cp4ba.yaml missing object for workflow_workstreams

### ISSUE THREAD

**Issue by techietav** [IBM/cloud-pak-deployer#491]
**Describe the bug**
In the provided sample config  cp4ba.yaml there is no object workflow_workstreams.enabled and the installer fails.  The example has workstreams.enabled
```
      workflow: # Business Automation Workflow (BAW) - https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=deployment-capabili
ties-production-deployments#concept_c2l_1ks_fnb__baw
        enabled: true
        optional_components:
          baw_authoring: true # Workflow Authoring (BAW) - always keep true if workflow pattern is chosen. BAW Runtime is not implemented.
      workstreams: # Automation Workstream Services (IAWS)
        enabled: false # Always false in this tool - this feature is not implemented

```

**To Reproduce**
Just run the install and it will fail with an error the Dict object workflow_workstreams is missing.

**Resolution**
Edit the yaml to include workflow_workstreams as below

```
workflow: # Business Automation Workflow (BAW)
        enabled: false
        optional_components:
          baw_authoring: false # Workflow Authoring (BAW)
workflow_workstreams: # Automation Workstream Services (IAWS)
        enabled: false # Always false in this tool - this feature is not implemented
```
