### ISSUE TITLE
Watsonxaiifm patched incorrectly

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#593]
**Describe the bug**
When patching the Watsonxaiifm CR with the models to be installed, an error occurs. Definition in deployer:
```
  - name: watsonx_ai
    description: watsonx.ai
    state: installed
    models:
    - model_id: google-flan-t5-xxl
      state: removed
    - model_id: google-flan-ul2
      state: removed
    - model_id: eleutherai-gpt-neox-20b
      state: installed
    - model_id: ibm-granite-13b-chat-v1
      state: removed
    - model_id: ibm-granite-13b-instruct-v1
      state: removed
    - model_id: meta-llama-llama-2-70b-chat
      state: removed
    - model_id: ibm-mpt-7b-instruct2
      state: removed
    - model_id: bigscience-mt0-xxl
      state: removed
    - model_id: bigcode-starcoder
      state: removed
```

Error:
```
  stderr: 'Error from server (BadRequest): error decoding patch: invalid character '','' looking for beginning of value'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

Command that is being executed:
```
oc patch Watsonxaiifm watsonxaiifm-cr \
  -n cpd \
  --type=merge \
  --patch '{"spec": {"install_model_list": [,"ibm-mpt-7b-instruct2"] } }'
```

There is an extra comma at the beginning of the list. This first comma should be skipped.

**Workaround**
Place the model(s) to be installed at the beginning of the list.
