### ISSUE TITLE
Building image steps no longer work

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#606]
**Describe the bug**
The steps in this doc link: https://ibm.github.io/cloud-pak-deployer/50-advanced/run-on-openshift/build-image-and-run-deployer-on-openshift/#build-deployer-image-and-push-to-the-internal-registry no longer work as the build arguments are missing.

**Fix**
Add the following to the build strategy:
```
dockerStrategy:
      buildArgs:
        - name: "CPD_OLM_UTILS_V1_IMAGE"
          value: "[icr.io/cpopen/cpd/olm-utils:latest](http://icr.io/cpopen/cpd/olm-utils:latest)"
        - name: "CPD_OLM_UTILS_V2_IMAGE"
          value: "[icr.io/cpopen/cpd/olm-utils-v2:latest](http://icr.io/cpopen/cpd/olm-utils-v2:latest)"
```
