### ISSUE TITLE
Enable storage classes for Fusion HCI

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#656]
When deploying watsonx or CP4D on Fusion HCI the following storage classes are available:

```
  openshift_storage:
  - storage_name: ibm-storage
    storage_type: custom
    ocp_storage_class_file: ibm-storage-fusion-cp-sc
    ocp_storage_class_block: ibm-storage-fusion-cp-sc
```

Create storage_type `fusion-hci` that will default file and block storage to `ibm-storage-fusion-cp-sc`.
