### ISSUE TITLE
GitHub rating issue when downloading clients

### ISSUE THREAD

**Issue by ibmmarkham** [IBM/cloud-pak-deployer#662]
**Describe the bug**
I am reporting the installing issue on behalf of KC Morrison since seems he is not able to log an issue directly.

The problem is described as the following:
In step name: Get current version number of clouctl

Which is in repo and file: https://github.com/IBM/cloud-pak-deployer/blob/main/automation-roles/99-generic/cloudctl/cloudctl-download/tasks/main.yml

The tags do not permit including an authentication token.  Our automated process always clones the latest version of this repo and then tries to use it.  Without a way to implement the token, we consistently get a rate-limit error on this step.

We have had to break our automation in order to work around this error.  We pause between the cloning of the repo, and execution of the repo, to give ourselves a chance to CHANGE what the repo delivered.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fketelaars** [comment]
@ibmmarkham removed the e-mail address from the issue.

**Comment by fketelaars** [comment]
@ibmmarkham I need more details on the download error, can you please ping me on Slack?

**Comment by fketelaars** [comment]
Change to be implemented:

- [ ] Allow user to specify the GitHub PAT in a vault secret: `github-ibm-pat`
- [ ] Update the download tasks to specify the github.com PAT if one is found in the vault

```
name: Get current version number of clouctl
    uri:
      url: https://api.github.com/repos/IBM/cloud-pak-cli/releases/latest
      return_content: yes
      method: GET
      status_code: 200
      headers:
        Authorization: "Bearer <github-ibm-pat secret>"
    register: _cloudctl_version
```
