### ISSUE TITLE
Update sample configurations with openshift.gpu.install

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#667]
**Describe the bug**
Some of the sample OopenShift configuration files do not have the `openshift.gpu.install` property.

```
openshift:
- name: "{{ env_id }}"
  ocp_version: 4.8
  cluster_name: "{{ env_id }}"
  domain_name: example.com
  gpu:
    install: False
```

Make sure that this property exists in all examples.
