### ISSUE TITLE
Add Cloud Native Toolkit bootstrap to OpenShift configuration

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#68]
To provide a Quickstart to the Cloud Native Toolkit (GitOps deployment), provide an option to bootstrap the toolkit as part of OpenShift configuration.

```
openshift:
- name: "{{ env_id }}"
  ocp_version: 4.8
  compute_flavour: bx2.16x64
  compute_nodes: 3
  infrastructure:
    type: vpc
    vpc_name: "{{ env_id }}"
    subnets: 
    - "{{ env_id }}-subnet-zone-1"
    - "{{ env_id }}-subnet-zone-2"
    - "{{ env_id }}-subnet-zone-3"
    cos_name: "{{ env_id }}-cos"
  cloud_native_toolkit: True
  openshift_storage:
  - storage_name: ocs-storage
    storage_type: ocs
    ocs_storage_label: ocs
    ocs_storage_size_gb: 500
    ocs_version: 4.8.0
```

New property `cloud_native_toolkit` is `False` by default. When set to `True`, the deployer installs the toolkit from GitHub repo:
https://github.com/cloud-native-toolkit/multi-tenancy-gitops

- [ ] Install ArgoCD operator and wait for CSV to be created
- [ ] Create ArgoCD instance in `openshift-gitops` project
