### ISSUE TITLE
CPD4.8.5: Block storage class required  at setup-instance-topology command

### ISSUE THREAD

**Issue by israel-a-vizcarra** [IBM/cloud-pak-deployer#691]
**Describe the bug**
setup-instance-topology  command in cpd4.8.5 installation now requires a block storage class , as stated at:

https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-installing-cloud-pak-foundational-services#taskinstall-platform-topology__steps__1

Modification to the following files required

cloud-pak-deployer/automation-roles/50-install-cloud-pak/cp4d/cp4d-cluster/templates/setup-instance-topology.j2
```
set -o pipefail
setup-instance-topology \
    --cpd_operator_ns={{ current_cp4d_cluster.operators_project | default('cpd-operators') }} \
    --cpd_instance_ns={{ current_cp4d_cluster.project }} \
    --release={{ current_cp4d_cluster.cp4d_version }} \
    --block_storage_class= {{ ocp_storage_class_block }} \  #<<<<<<<<<<
    --license_acceptance=true 2>&1 | tee {{ status_dir }}/log/{{ current_cp4d_cluster.project }}-setup-instance-topology.log
```
cloud-pak-deployer/automation-roles/50-install-cloud-pak/cp4d/cp4d-cluster/tasks/openshift-prepare-project.yml
```
  - name: Run script to setup instance topology, output can be found in {{ status_dir }}/log/{{ current_cp4d_cluster.project }}-setup-instance-topology.log
    shell: |
      {{ status_dir }}/cp4d/{{ current_cp4d_cluster.project }}-setup-instance-topology.sh

  when:
  - current_cp4d_cluster.cp4d_version >= '4.7.0' and  current_cp4d_cluster.cp4d_version < '4.8.0'

```
