### ISSUE TITLE
watsonx Orchestrate sample config is incomplete

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#698]
**Describe the bug**
When trying to install watsonx Orchestrate using deployer, the following error is thrown:
```
TASK [cp4d-cartridge-install : Run apply-olm command to install watsonx Orchestrate subscriptions, logs are in /Data/cpd-status/log/cpd-apply-olm-wxo.log] ***
Tuesday 23 April 2024  17:14:27 +0000 (0:00:00.051)       0:34:36.346 ********* 
changed: [localhost]

TASK [cp4d-cartridge-install : set_fact] ***************************************
Tuesday 23 April 2024  17:20:18 +0000 (0:05:50.969)       0:40:27.316 ********* 
fatal: [localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'app_connect'
  
    The error appears to be in '/cloud-pak-deployer/automation-roles/50-install-cloud-pak/cp4d/cp4d-cartridge-install/tasks/cp4d-prep-watsonx-orchestrate.yml': line 29, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - set_fact:
      ^ here
```

**Solution**
The example configuraiton is incomplete, it should be:
```
  - name: watsonx_orchestrate
    description: watsonx.orchestrate
    app_connect:
      app_connect_project: ibm-app-connect
      app_connect_case_version: 11.3.0
      app_connect_channel_version: v11.3
    state: removed
```
