### ISSUE TITLE
Provide CPFS scaling profile option for CP4D

### ISSUE THREAD

**Issue by techietav** [IBM/cloud-pak-deployer#718]
**Is your feature request related to a problem? Please describe.**
On a large deployment of CP4D/watsonx the underlying CPFS components need to be scaled up to avoid performance issues and instability.  This has to be done manually.

**Describe the solution you'd like**
The deployer config YAML could contain a size variable like used in the CP4BA deployment.

 cpfs_profile_size: small # Profile size which affect replicas and resources of Pods of CPFS as per https://www.ibm.com/docs/en/cpfs?topic=operator-hardware-requirements-recommendations-foundational-services

**Comment by fketelaars** [comment]
@techietav can you elaborate on how to set the size _after_ installation. CPFS are installed as part of the CP4D control plane and initial installation assumes `small` size. I tried setting the `CommonService` size to `medium`, but this doesn't seem to change anything (no additional replicas, ...). Any advice?

**Comment by techietav** [comment]
On the Fusion HCI system there are over 1400 pods so I believe I should be using medium at least. https://www.ibm.com/docs/en/cloud-paks/foundational-services/4.6?topic=installer-hardware-requirements-recommendations-foundational-services
In ccs-cr you can set the size which is small by default.
```
spec:
  autoScaleConfig: false
  blockStorageClass: ibm-storage-fusion-cp-sc
  fileStorageClass: ibm-storage-fusion-cp-sc
  global_search_reindex_job_resources_limits_memory: 2Gi
  license:
    accept: true
  scaleConfig: **small**
  storageClass: ibm-storage-fusion-cp-sc
  version: 8.5.0
```
