### ISSUE TITLE
Use different DataScienceCluster for CP4D 5.0.3+

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#812]
**Describe the bug**
As from CP4D 5.0.3, a different DataScienceCluster is needed to run watsonx.ai. https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2.11/html/installing_and_uninstalling_openshift_ai_self-managed/preparing-openshift-ai-for-ibm-cpd_prepare-openshift-ai-ibm-cpd#managing-openshift-ai-components-using-cli-ibm-cpd_prepare-openshift-ai-ibm-cpd

The following is now needed:
```
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster 
metadata:
  name: default-dsc
spec:
  components:
    codeflare:
      managementState: Removed
    dashboard:
      managementState: Removed
    datasciencepipelines:
      managementState: Removed
    kserve:
      managementState: Managed
      defaultDeploymentMode: RawDeployment 
      serving:
        managementState: Removed 
        name: knative-serving
    kueue:
      managementState: Removed
    modelmeshserving:
      managementState: Removed
    ray:
      managementState: Removed
    trainingoperator:
      managementState: Managed 
    trustyai:
      managementState: Removed
    workbenches:
      managementState: Removed
```
