### ISSUE TITLE
Creating OCS cluster in OCP 4.15+ IBM ROKS fails

### ISSUE THREAD

**Issue by techietav** [IBM/cloud-pak-deployer#830]
**Describe the bug**
Installing CP4BA on IBM ROKS vpc with ocs defined.  The ODF operator is installed and parameters are not passed correctly so that it installs with defaults and creates an ocscluster called ocscluster-auto on all worker nodes, not just the storage pool. The deployer then tries to creates an ocscluster called ocs and fails as there is an existing ocs cluster.

**To Reproduce**
Run the CP4BA pattern on IBM ROKS vpc

**Expected behavior**
The ODF operator should get installed without creating a default ocs cluster.

**Comment by techietav** [comment]
47837 fatal: [localhost]: FAILED! => changed=true
  47838   cmd: |-
  47839     ibmcloud oc cluster addon enable openshift-data-foundation \
  47840         --cluster vantage-2 \
  47841         --param "odfDeploy=false" \
  47842         -f  --version 4.16
  47843   delta: '0:00:00.467315'
  47844   end: '2024-11-04 17:08:41.116750'
  47845   invocation:
  47846     module_args:
  47847       _raw_params: |-
  47848         ibmcloud oc cluster addon enable openshift-data-foundation \
  47849             --cluster vantage-2 \
  47850             --param "odfDeploy=false" \
  47851             -f  --version 4.16
  47852       _uses_shell: true
  47853       argv: null
  47854       chdir: null
  47855       creates: null
  47856       executable: null
  47857       removes: null
  47858       stdin: null
  47859       stdin_add_newline: true
  47860       strip_empty_ends: true
  47861       warn: true
  47862   msg: non-zero return code
  47863   rc: 1
  47864   start: '2024-11-04 17:08:40.649435'
  47865   stderr: |-
  47866     FAILED
  47867     Passing installation options is not valid for openshift-data-foundation.
  47868   stderr_lines: <omitted>

**Comment by fketelaars** [comment]
@techietav can you please include the `openshift` configuration you used. I recently deployed a ROKS cluster with this configuration and it worked:

```
---
global_config:
  environment_name: sample
  cloud_platform: ibm-cloud
  ibm_cloud_region: eu-de
  env_id: fk-ksa-demo

# vault:
#   vault_type: ibmcloud-vault
#   vault_authentication_type: api-key
#   vault_url: https://caabac85-40ab-40d5-965a-a7e9debd5e37.eu-de.secrets-manager.appdomain.cloud

provider:
- name: ibm
  region: "{{ ibm_cloud_region }}"

resource_group:
- name: "Default" # should exist already

security_rule:
- name: https
  tcp: {port_min: 443, port_max: 443}
- name: ssh
  tcp: {port_min: 22, port_max: 22}

vpc:
- name: "{{ env_id }}"
  allow_inbound: ['ssh']

address_prefix:
- name: "{{ env_id }}-zone-1"
  zone: "{{ ibm_cloud_region }}-1"
  cidr: 10.231.0.0/26
- name: "{{ env_id }}-zone-2"
  zone: "{{ ibm_cloud_region }}-2"
  cidr: 10.231.0.64/26
- name: "{{ env_id }}-zone-3"
  zone: "{{ ibm_cloud_region }}-3"
  cidr: 10.231.0.128/25 

subnet:
- name: "{{ env_id }}-subnet-zone-1"
  address_prefix: "{{ env_id }}-zone-1"
  ipv4_cidr_block: 10.231.0.0/26
- name: "{{ env_id }}-subnet-zone-2"
  address_prefix: "{{ env_id }}-zone-2"
  ipv4_cidr_block: 10.231.0.64/26
- name: "{{ env_id }}-subnet-zone-3"
  address_prefix: "{{ env_id }}-zone-3"
  ipv4_cidr_block: 10.231.0.128/26

cos:
- name: "{{ env_id }}-cos"
  plan: standard
  location: global

openshift:
- name: "{{ env_id }}"
  ocp_version: "4.15"
  compute_flavour: bx2.16x64
  compute_nodes: 3
  infrastructure:
    type: vpc
    vpc_name: "{{ env_id }}"
    subnets: 
    - "{{ env_id }}-subnet-zone-1"
    - "{{ env_id }}-subnet-zone-2"
    - "{{ env_id }}-subnet-zone-3"
    cos_name: "{{ env_id }}-cos"
  openshift_storage:
  - storage_name: ocs-storage
    storage_type: ocs
    ocs_storage_label: ocs
    ocs_storage_size_gb: 500
    ocs_version: "4.15.0"
```

Please note that the `ocs_version` must be specified as "v.r.0", We should probably consider enforcing this through the deployer configuration checks.
