### ISSUE TITLE
Deployer ignoring `processor_architecture: arm64` setting to install OpenShift using ARM64 Processors for AWS IPI

### ISSUE THREAD

**Issue by Alan111S** [IBM/cloud-pak-deployer#871]
Since 4.12, OpenShift has supported ARM64 processors, so I was trying to install a 4.16 cluster that used them on AWS

To reproduce, configure openshift yaml file to use `m6g` instance types and set  `processor_architecture: arm64`

```
---
global_config:
  environment_name: beta1
  cloud_platform: aws
  aws_region: ap-southeast-2
  env_id: beta1
  confirm_destroy: True

nfs_server:
- name: "{{ env_id }}-elastic"
  infrastructure:
    aws_region: "{{ aws_region }}"

openshift:
- name: "{{ env_id }}"
  ocp_version: '4.16'
  domain_name: dm-cpd.mettleci.cloud
  control_plane_flavour: m6g.xlarge
  control_plane_nodes: 3
  control_disk_size_gb: 120
  compute_flavour: m6g.2xlarge
  compute_nodes: 3
  compute_disk_size_gb: 120
  infrastructure:
    type: self-managed
    processor_architecture: arm64
    aws_region: "{{ aws_region }}"
    multi_zone: True
    machine_cidr: 10.1.0.0/16
  openshift_storage:
  - storage_name: "{{ env_id }}-elastic"
    storage_type: aws-elastic
```

**Expected behavior**
Expected the OpenShift Cluster to be created with ARM64 Instances

**Actual behavior**
The Deployer gave an error message which indicated it ignored the `processor_architecture: arm64` statement and complained that you can't use m6g instance types with processor_architecture: amd64
