### ISSUE TITLE
WA does not provision when backingstore is underpinned by PVC

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#907]
**Describe the bug**
When installing Watson Assistant on a cluster where the NooBaa BackingStore is underpinned by PVC, the `wa-nlu*` pods keep restarting. Additionally, in the `openshift-storage` namespace, the `noobaa-endpoint` and `noobaa-operator` pods fail and restart frequently, more or less in sync with the `wa-nlu*` pods.

**Comment by fketelaars** [comment]
Debug - patching NooBaa:
```
oc patch -n openshift-storage backingstore noobaa-default-backing-store --type=merge --patch='{"spec":{"pvPool":{"numVolumes": 1, "resources":{"limits":{"memory": "8Gi"}}}}}'

oc patch -n openshift-storage storageclusters.ocs.openshift.io ocs-storagecluster --type merge --patch '{"spec": {"resources": {"noobaa-core": {"limits": {"memory": "8Gi"},"requests": {"memory": "8Gi"}},"noobaa-db": {"limits": {"memory": "8Gi"},"requests": {"memory": "8Gi"}},"noobaa-endpoint": {"limits": {"memory": "8Gi"},"requests": {"memory": "8Gi"}}}}}'
```

**Comment by fketelaars** [comment]
Update the wa-nlu deployments to have a higher ephemeral storage limit:
```
        resources:
          limits:
            cpu: "4"
            ephemeral-storage: 800Mi
            memory: 2Gi
          requests:
            cpu: 100m
            ephemeral-storage: 300Mi
            memory: 2Gi
```

Before doing this, scale down the WA operator to avoid the deployment to be reverted.
