### ISSUE TITLE
Optimize deploy not working when global_config.optimize_deploy set

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#942]
**Describe the bug**
I have the following configuration:
```
---
global_config:
  environment_name: sample
  cloud_platform: existing-ocp
  env_id: cpd-511
  confirm_destroy: False
  optimize_deploy: True
```

Still, deployer tries to set up the instance if it already exists. In the debug log, _cpd_optmize_deploy, seems to have a strange value:
```
ok: [localhost] => (item={'key': '_confirm_destroy', 'value': '{{ (global_config.confirm_destroy | default(False)) or (confirm_destroy | default(False)) }}'})
ok: [localhost] => (item={'key': '_cpd_optimize_deploy', 'value': '{{ (global_config.optimize_deploy | default(False) | bool) or (cpd_optimize_deploy | default(False) | bool) }}'})
```

Maybe this is due to the Ansible version, this did work before.
